apiVersion: v1
kind: Secret
metadata:
  name: loantrack-db-secret
  namespace: loantrack
type: Opaque
stringData:
  POSTGRES_DB: loantrack
  POSTGRES_USER: loantrack_user
  POSTGRES_PASSWORD: change_me